### ISSUE TITLE
Teammember in die Gruppe holen

### ISSUE THREAD

**Issue by zeljkobekcic** [Wiredaemon/obligatory#1]
@Wiredaemon 
Moin moin,

ich nehme an dass du unser "Betreuer" fuer das Abschlussprojekt bist.

Zwei von unseren Teammitgliedern haben es nicht geschafft sich anzumelden ueber den Link welcher sich in der Aufgbenbeschreibung befindet.

Kannstu du diese bitte hinzufuegen?
https://github.com/nafoe
https://github.com/shaman78

Danke sehr :+1:

**Comment by Wiredaemon** [comment]
Halli hallo,

mit der Annahme liegst du ganz richtig.
Ich schau mal was sich machen lässt ;)

**Comment by Wiredaemon** [comment]
Ok. Es sieht so aus, als ob ich nicht die Berechtigungen besitze jemanden in ein Team zuzuweisen.
Den Knopf hab ich nur bei den Test-Repos.

Wo liegt denn eigentlich das Problem?
Solange ihr in der Propra16 Organisation seid, solltet ihr doch selbständig einem team beitreten können.

**Comment by Wiredaemon** [comment]
Hier der Link mit der team übersicht.
https://github.com/orgs/ProPra16/teams

Aber falls das auch nicht geht, schreibt noch einmal, dann assigne ich einfach jemanden, der auf jeden fall alle Rechte hat ;)

**Comment by zeljkobekcic** [comment]
"Problem" ist fertig, ich erlaube mit mal dieses Issue zu schliessen.

**Comment by Wiredaemon** [comment]
ja. war ja sowieso das falsche repo :smile:
